---
title: "R Assignment 1: Causal Parameters & Simulations in R"
author: "Your Name Here"
date: "The Date"
output: pdf_document
---

```{r echo=F}
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)
```


# 2  Steps 1-2 of the Roadmap

\textbf{Step 1: Causal model representing real knowledge}

(a) Draw the accompanying directed acyclic graph (DAG).

(b) Are there any exclusion restrictions?  Recall we are working with recursive (time-ordered) structural causal models. 

(c) Are there any independence assumptions on the distribution of unmeasured factors $\mathbb{P}_U$?

\textbf{Step 2: Counterfactuals $\&$ causal parameter}

(a) Define the counterfactual outcomes of interest with formal notation and in words. 

(b) How are counterfactuals derived?

(c) Suppose we are interested in the average treatment effect.  Specify the target causal parameter. Use formal notation as well as explain in words. 

# 3  A specific data generating process

## 3.1 Closed form evaluation of the target causal parameter

\textbf{Evaluate the target causal parameter $\Psi^*(\mathbf{P}^*)$ in closed form (i.e., by hand) for this data generating process.}

## 3.2 Translating this data generating process for $\mathbb{P}^*$ into simulations, generating counterfactual outcomes and evaluating the target causal parameter. 

\textbf{1. First set the seed to 252.}

```{R s3.2q1}

```

\textbf{2. Set \texttt{n=50,000} as the number of i.i.d. draws from the data generating process.}

```{R s3.2q2}

```

\textbf{3. Simulate the background factors \textit{U}}.  Note the syntax for $\texttt{rnorm}$.

```{R s3.2q3}

```

\textbf{4.  Evaluate the structural equations $\mathcal{F}$ to deterministically generate the endogenous nodes $X$.} Recall that the $logit^{-1}$ function is given by the $\texttt{plogis}$ function in $\texttt{R}$.

```{R s3.2q4}

```

\textbf{5. Intervene to set the supplement to RUTF $(A=1)$ and generate counterfactual outcomes $Y_1$ for $n$ units.  Then intervene to set the supplement to the standard $(A=0)$ and generate counterfactual outcomes $Y_0$ for $n$ units.}

```{R s3.2q5}

```

\textbf{6. Create a data frame \texttt{X} to hold the values of the endogenous factors $(W_1, W_2,A,Y)$ and the counterfactual outcomes $Y_1$ and $Y_0$. The rows are the $n$ children and the columns are their characteristics. Use the $\texttt{head}$ and $\texttt{summary}$ to examine the resulting data.  Does the counterfactual value $Y_a$ equal the observed $Y$ when $A=a$?}

```{R s3.2q6}

```

\textbf{7. Using these simulations, evaluate the causal parameter $\Psi^*(\mathbb{P}^*)$ for this population of 50,000 units.}

```{R s3.2q7}

```

\textbf{8. Interpret $\Psi^*(\mathbb{P}^*)$.}

# 4  Defining the target causal parameter with a working MSM

## 4.1 A specific data generating process

\textbf{1. For $n=5,000$ children, generate the background factors $U$ and the pre-intervention covariates $(V, W1, W2)$.  Then set $A=1$ to generate the counterfactual weight gain under RUTF $Y_1$. Likewise, set $A=0$ to generate the counterfactual weight gain under the standard supplement $Y_0$.}

```{R s4.1q1}

```

\textbf{2. Create a data frame $\texttt{X.msm}$ consisting of age $V$, the set treatment levels $a$, and the corresponding outcomes $Y_a$.}

$$
X_{MSM} = (V, a, Y_a) = \left( 
\begin{matrix} 
V(1) & 1 & Y_1(1) \\
V(2) & 1 & Y_1(2) \\
\vdots & \vdots & \vdots \\
V(n) & 1 & Y_1(n) \\
V(1) & 0 & Y_1(1) \\
V(2) & 0 & Y_1(2) \\
\vdots & \vdots & \vdots \\
V(n) & 0 & Y_1(n) \\
\end{matrix}
\right)
$$

where $V(i)$ and $Y_a(i)$ denote the age and counterfactual outcome for the $i^{th}$ subject.  See $\texttt{R}$ lab 1 for a similar example. 

```{R s4.1q2}

```

\textbf{3. Evaluate the target causal parameter.}  We have defined the target parameter using the last square projection (i.e., with the L2 loss function).  Use the $\texttt{glm}$ function to fit the coefficients of the working MSM.  Specifically, regress the counterfactual outcomes $Y_a$ on $a$ and $V$ according to the working MSM.  Be sure to specify the argument: $\texttt{data = X.msm}$.

```{R s4.1q3}

```

\textbf{4. Interpret the results.}

\textbf{5.  Bonus:} Plot of the counterfactual outcomes $Y_a$ as a function of age $(V)$ and treatment group $(a)$.

```{R s4.1q5}

# Optional: bonus section 

```